baseURL = "https://rbonichon.github.io"
languageCode = "en-us"
title = "RB"
# theme = "rb"

# include content marked as draft
buildDrafts =                 false
# include content with publishdate in the future
buildFuture =                 false

# config file (default is path/config.yaml|json|toml)
config = "config.toml"
contentDir = "content"

publishDir = "docs"

[taxonomies]
  category = "categories"
  tag = "tags"

