#+title: Automated theorem proving for propositional logic (part 1)
#+filetags: :rust:logic:

This is the first part of a series covering automated theorem proving techniques
for propositional logic. The series aims at being a foundational and practical
guide introduction to this subject. That means, we will implement everything in
=rust=[fn:1]. 

This first part will be dedicated to the abstract syntax of propositional logic,
and its concrete counterpart, together with its parsing and pretty-printing.

* Abstract syntax

* Concrete syntax

** Definition

** Parsing

** Printing

** What goes around comes around

   A pretty-printer and parser needs to be bound by some form of inverse
   relation.  Let =s' = print(parse(s))=. Then either we have =s' = s=, or, more
   usually, a weaker form of equality on abtract syntax trees =parse(s') =
   parse(s)=, since the former might hold only for a subset of parsable inputs.

   For example, in propositional logic $(P \land Q) \lor R$ reads the same as $P
   \land Q \lor R$ but the string representation is different. If we accept
   parentheses but permit omitting them, we can only enforce the weaker
   relation.

* Footnotes

[fn:1] In all honesty, I'd have chosen =ocaml= on pure bias, but John Harrison
has this more than covered in its [[https://www.goodreads.com/book/show/7475215-handbook-of-practical-logic-and-automated-reasoning][Handbook of Practical Logic and Automated
Reasoning]].
